Stage_10
KinCadeFoster/LearnEnglishTelegramBot pull request #10
Opened 2024-07-11 19:39 UTC by KinCadeFoster

- доработка бота

2024-07-12 19:07 UTC, danelyan requested changes
Круто! Почти все учтено ))

Три момента:

1. Как остановить процесс изучения слов? Давай выход в меню добавим последним пунктом
2. Давай разместим в столбик, больше влезет
3. Давай уберем кавычки из статистики:

> 
> "Выучено 0 из 900 слов. 
>  Это 0% от всех слов в базе данных!"


<img width="446" alt="Screenshot 2024-07-12 at 15 11 51" src="https://github.com/user-attachments/assets/d2954eec-bb70-43bc-99a1-e2b834c40785">

2024-07-12 19:07 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +    json: Json
Обрати внимание, Json можно создать внутри TelegramBotService, и не пробрасывать его извне каждый раз

2024-07-12 19:07 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        text?.lowercase() == "/start" -> {
`/start` лучше унести в константы

2024-07-13 18:09 UTC, KinCadeFoster commented on src/main/kotlin/Telegram.kt
> +        text?.lowercase() == "/start" -> {
done

2024-07-13 19:37 UTC, KinCadeFoster commented on src/main/kotlin/Telegram.kt
> +    json: Json
done

2024-07-16 05:21 UTC, danelyan requested changes

2024-07-16 05:21 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +                row.clear()
круто! Вот тебе еще альтернативный вариант с использованием chunked(N). Эта функция разбивает список на подсписки в которых N элементов:
```Kotlin
       inlineKeyboard.addAll(
            variants.chunked(2).mapIndexed { rowIndex, words: List<Word> ->
                words.mapIndexed { colIndex, word ->
                    println(rowIndex * 2 + colIndex)
                }
            }
        )
```

2024-07-16 05:21 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        val response: HttpResponse<String> = client.send(request, HttpResponse.BodyHandlers.ofString())
Вот эти места (выполнение сетевых запросов при помощи `send()`) - не защищены, поэтому любая сетевая проблема приведет к падению приложения. Попробуй выключить интернет ненадолго, запустив бота локально.

Точно также может стать недоспуным сервер телеграма.
Можно сделать просто обертку типа: `runCatching  { client.send(...) }`

И пропускать итерацию цикла, если есть запрос выполнен не успешно

2024-07-18 05:51 UTC, danelyan approved these changes
![yougotthis-martini](https://github.com/Gaileks/LearnEnglishWordsTelegramBot/assets/7125622/3339b61b-9b81-484f-989b-a6e73733be08)

Поздравляю! Ты сделал бота на Kotlin.

Основная часть работы пройдена. Теперь этот бот твой - можешь развивать его как хочешь. Дальше я подготовил тебе развилку из 6 простеньких доработок, все они уже в боте. Однако можешь не ограничиваться только ими, любые идеи приветствуются, просто опиши в личку и мы продумаем детали. 

Дальше как обычно - создаешь Pull Request (даже если что-то еще не работает - шлешь), а я пишу что можно улучшить.

2024-07-18 12:22 UTC, merged