Stage_4
KinCadeFoster/LearnEnglishTelegramBot pull request #4
Opened 2024-06-13 01:43 UTC by KinCadeFoster

- Реализовано для режима изучения слов отображение загаданного и четыре перемешанных невыученных слова.
- Для случая когда неизученных слов меньше чем 4, берем слова из общего списка с изыченными словами
- Добавлена проверка на невыученные слова. Если таких нет, отображать “Вы выучили все слова”.

2024-06-16 07:39 UTC, danelyan requested changes

2024-06-16 07:39 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    return dictionary.filter { it.correctCount < 3 }
3 можно вынести в константы

2024-06-16 07:39 UTC, danelyan commented on src/main/kotlin/Main.kt
> +fun updateCorrectCount(dictionary: List<Word>, learningWord: List<Word>) {
этот метод излишен. У тебя уже есть слово которое является правильным. Подробнее выше отписал

2024-06-16 07:39 UTC, danelyan commented on src/main/kotlin/Main.kt
>  fun getUserStatistics(dictionary: List<Word>) {
Давай 2 вынесем в константы с нормальным именем.
Точнее, вынесем 3 и воспользуемся >=

2024-06-16 07:39 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        if (userAnswer !in 1..4) {
а если вариантов больше 4? Давай вынесем в константу

2024-06-16 07:39 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        val answers = takeShuffleElements(dictionary, unlearnedWords, value = 3, learningWord)
3 - в константы

2024-06-16 07:39 UTC, danelyan commented on src/main/kotlin/Main.kt
> +        val answers = tempDictionary.shuffled().take(value) + learningWord
тут много повторяющегося кода.
Можем его обобщить?
К примеру 83, 84 и 85 строка идентичны 87, 88, 89

2024-06-17 08:18 UTC, KinCadeFoster commented on src/main/kotlin/Main.kt
> +    return dictionary.filter { it.correctCount < 3 }
добавил константу

2024-06-17 08:18 UTC, KinCadeFoster commented on src/main/kotlin/Main.kt
> +fun updateCorrectCount(dictionary: List<Word>, learningWord: List<Word>) {
удалил метод

2024-06-17 08:18 UTC, KinCadeFoster commented on src/main/kotlin/Main.kt
>  fun getUserStatistics(dictionary: List<Word>) {
добавил константу

2024-06-17 08:19 UTC, KinCadeFoster commented on src/main/kotlin/Main.kt
> +        if (userAnswer !in 1..4) {
добавил константу

2024-06-17 08:19 UTC, KinCadeFoster commented on src/main/kotlin/Main.kt
> +        val answers = takeShuffleElements(dictionary, unlearnedWords, value = 3, learningWord)
добавил константу

2024-06-17 08:19 UTC, KinCadeFoster commented on src/main/kotlin/Main.kt
> +        val answers = tempDictionary.shuffled().take(value) + learningWord
добавил метод getAnswerChoices

2024-06-19 09:43 UTC, danelyan approved these changes
Хорошо. Дальше еще немного порефакторим )

2024-06-19 15:10 UTC, merged