Stage_5
KinCadeFoster/LearnEnglishTelegramBot pull request #5
Opened 2024-06-19 15:35 UTC by KinCadeFoster

- добавил функцию сохранения изменений в файл при правильном ответе
- добавил функцию обновления счетчика правильных ответов updateCorrectCount

2024-06-20 04:43 UTC, danelyan requested changes

2024-06-20 04:43 UTC, danelyan commented on src/main/kotlin/Main.kt
> +            if (answers[userAnswer - 1].ruWord == learningWord[0].ruWord) {
Давай для изучаемого слова сделаем отдельную переменную, а не будем считать, что первый элемент списка learningWord - это изученное слово.

2024-06-20 04:43 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    learningWord[0].correctCount++
этот метод в целом не нужен. Когда для изучаемого слова у тебя будет отдельная переменная (кстати, для изучаемого слова, я бы оставил переменную learningWord, а для показываемых 4 слов - questionWords нпример), просто можешь делать `learningWord.correctCount++`.

2024-06-20 07:18 UTC, KinCadeFoster commented on src/main/kotlin/Main.kt
> +    learningWord[0].correctCount++
Меня смутил этот пункт "Создать функцию сохранения обновленных результатов в словарь и вызвать ее при каждом правильном ответе" не совсем понятно к чему это относилось к обновлению файла или самого словаря, поэтому добавил updateCorrectCount. Удалю, видимо тут речь про сам файл.

2024-06-21 09:51 UTC, danelyan commented on src/main/kotlin/Main.kt
> +    learningWord[0].correctCount++
да, речь про сам файл

2024-06-23 05:29 UTC, danelyan approved these changes

2024-06-23 07:03 UTC, merged