Stage_6
KinCadeFoster/LearnEnglishTelegramBot pull request #6
Opened 2024-06-23 20:17 UTC by KinCadeFoster

- рефакторинг всего кода

2024-06-24 05:29 UTC, danelyan requested changes

2024-06-24 05:29 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        val learnedWords = dictionary.count { it.correctCount >= WORD_LEARNED_LIMIT }
Давай сделаем константы WORD_LEARNED_LIMIT и NEEDED_WRONG_ANSWERS полями класса LearnWordsTrainer, более того - вынесем в его основной конструктор

2024-06-24 05:29 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        return unLearningWord.shuffled().take(1).first()
тут достаточно: `unLearningWord.random()`
И в целом можно убрать метод `takeLearningWord(...)`.
Конструкция `unLearningWord.random()` будет выглядеть сама по себе вполне читаемой

2024-06-24 05:29 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +    private fun updateWordsFile(dictionary: List<Word>) {
может просто назовем saveDictionary()?
И еще, незачем передавать dictionary в качестве параметра, это же теперь поле класса. Используй его напрямую. Обрати внимание и на другие места

2024-06-24 11:00 UTC, KinCadeFoster commented on src/main/kotlin/LearnWordsTrainer.kt
> +        val learnedWords = dictionary.count { it.correctCount >= WORD_LEARNED_LIMIT }
Done

2024-06-24 11:05 UTC, KinCadeFoster commented on src/main/kotlin/LearnWordsTrainer.kt
> +        return unLearningWord.shuffled().take(1).first()
удалил метод takeLearningWord(...), заменил на unLearningWord.random()

2024-06-24 11:19 UTC, KinCadeFoster commented on src/main/kotlin/LearnWordsTrainer.kt
> +    private fun updateWordsFile(dictionary: List<Word>) {
Done

2024-06-24 17:20 UTC, danelyan commented on src/main/kotlin/LearnWordsTrainer.kt
> +        val learnedWords = dictionary.count { it.correctCount >= WORD_LEARNED_LIMIT }
Можешь нажимать троеточие -> Hide -> Reason=Resolved

<img width="803" alt="Screenshot 2024-06-24 at 20 19 43" src="https://github.com/KinCadeFoster/LearnEnglishTelegramBot/assets/7125622/a4945cea-10a4-4b55-9cfc-2b009dec2cf0">

2024-06-26 08:56 UTC, danelyan approved these changes
Отлично! Идем дальше

2024-06-26 12:33 UTC, merged