Stage_8
KinCadeFoster/LearnEnglishTelegramBot pull request #8
Opened 2024-06-29 20:11 UTC by KinCadeFoster

- переписан парсинг update_id через Regex
- создал отдельную функцию для отправки сообщений sendMessage
- создал новое Regex выражение, чтобы добыть из апдейтов chatId
- если в боте отправить строку “Hello”, то в ответ бот отправляет сообщение “Hello"
- создал отдельный класс TelegramBotService с методами для взаимодействия с Telegram API

2024-07-01 04:31 UTC, danelyan requested changes

2024-07-01 04:31 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        val urlGetUpdates = "https://api.telegram.org/bot$botToken/getUpdates?offset=$updateId"
`https://api.telegram.org/bot` - можно вынести в константы

2024-07-01 04:31 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +    fun getUpdates(botToken: String, updateId: Int): String {
botToken можно передать в конструктор TelegramBotService, чтобы не прокидывать в каждый метод

2024-07-01 04:31 UTC, danelyan commented on src/main/kotlin/TelegramBotService.kt
> +        val client = HttpClient.newBuilder().build()
HttpClient можно сделать полем TelegramBotService, чтобы не создавать экземпляр при каждом сетевом вызове.
В целом, старайся отслеживать, когда у тебя в памяти создаются те или иные объекты

2024-07-01 04:31 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        val textRegex = "\"text\":\"([^\"]+)\"".toRegex()
Regex можно не создавать каждую итерацию цикла. Все регексы можно создать до запуска while

2024-07-02 16:38 UTC, KinCadeFoster commented on src/main/kotlin/TelegramBotService.kt
> +        val urlGetUpdates = "https://api.telegram.org/bot$botToken/getUpdates?offset=$updateId"
done

2024-07-02 16:40 UTC, KinCadeFoster commented on src/main/kotlin/TelegramBotService.kt
> +    fun getUpdates(botToken: String, updateId: Int): String {
done

2024-07-02 16:46 UTC, KinCadeFoster commented on src/main/kotlin/TelegramBotService.kt
> +        val client = HttpClient.newBuilder().build()
учту) вынес

2024-07-02 16:48 UTC, KinCadeFoster commented on src/main/kotlin/Telegram.kt
> +        val textRegex = "\"text\":\"([^\"]+)\"".toRegex()
done

2024-07-02 22:09 UTC, danelyan commented on src/main/kotlin/Telegram.kt
> +        val textRegex = "\"text\":\"([^\"]+)\"".toRegex()
В будущем можешь просто Resolve'ить комменты:

<img width="300" alt="Screenshot 2024-07-03 at 01 08 37" src="https://github.com/KinCadeFoster/LearnEnglishTelegramBot/assets/7125622/166e6481-8b85-43a6-bbcf-d4a6699bef26">

<img width="818" alt="Screenshot 2024-07-03 at 01 08 56" src="https://github.com/KinCadeFoster/LearnEnglishTelegramBot/assets/7125622/20b68627-79e0-421c-9bbf-960fd070613d">

2024-07-03 14:30 UTC, danelyan approved these changes

2024-07-04 13:35 UTC, merged